# -*- coding: utf-8 -*-
"""streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FPBSp4syWSlrNWiSfIxMYQ8NXdBdn87k
"""

import streamlit as st

st.write('Hello, *World!* :sunglasses:')